server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:fone-db}:${DB_PORT:3306}/${DB_DATABASE:fone}?&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:fone-flim-be}
    hikari:
      pool-name: test_pool
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        check_nullability: true
        use_sql_comments: true
        format_sql: true
        show_sql: true

  redis:
    host: ${REDIS_HOST:fone-redis}
    port: ${REDIS_PORT:6379}
