server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_DATABASE:fone}?&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:fone-flim-be}
    hikari:
      pool-name: test_pool
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        check_nullability: true
        use_sql_comments: true
        format_sql: false
        show_sql: false

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

credentials:
  sms:
    key: ${SMS_KEY:test}
    user-id: ${SMS_USER:test}
    sender: ${SMS_SENDER:test}

security:
  aws:
    senderEmail: ${SENDER_EMAIL:fyimbtmn@gmail.com}
    accessKey: ${AWS_ACCESS_KEY:test}
    secretKey: ${AWS_SECRET_KEY:test}
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jwt:
    secret: foneBackendSecretfoneBackendSecretfoneBackendSecret
    access-token-validity-in-seconds: 7200
    refresh-token-validity-in-seconds: 1209600
  oauth:
    naver:
      client-id: aU9oh1xxoC6uAMW48qCP
      client-secret: secret_placeholder

discord:
  question: ${DISCORD_QUESTION_URL:url}
  report: ${DISCORD_REPORT_URL:url}
  monitor: ${DISCORD_MONITOR_URL:https://discord.com/api/webhooks/1155356389045186670/fWAW9DVLczHR8q5IIfifgSu75pU3i1ALPqZwig2mspck5EttYUc-bItbOUD_d_nW10jR}
