name: Deploy API To Prod

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'chatting/**'
      - '.github/workflows/deploy-chatting-to-prod.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: make application-prod.yml
        run: |
          cd ./server/src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.PROPERTIES_PROD }}" > ./application-prod.yml
        shell: bash
      - name: Build with Gradle
        run: ./gradlew :server:bootJar -x test
      - name: Docker build
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker build -f docker/api.Dockerfile -t fone-backend .
          docker tag fone-backend sinkyoungdeok/fone-backend
          docker push sinkyoungdeok/fone-backend
      - name: Deploy Prod
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ubuntu
          password: ${{ secrets.LIGHTSAIL_PASSWORD }}
          port : 22
          script: |
            docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
            docker pull sinkyoungdeok/fone-backend
            docker-compose down 
            docker-compose up -d