name: Deploy Chatting To Prod

on:
  push:
    branches:
      - main
    paths:
      - 'chatting/**'
      - '.github/workflows/deploy-chatting-to-prod.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew
      - name: Make Prod Yml
        run: |
          cd ./chatting/src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.PROPERTIES_PROD }}" > ./application-prod.yml
        shell: bash
      - name: Build With Gradle
        run: ./gradlew :chatting:bootJar -x test
      - name: Docker Build And Push
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker build -f docker/chatting.Dockerfile -t fone-chatting .
          docker tag fone-chatting sinkyoungdeok/fone-chatting
          docker push sinkyoungdeok/fone-chatting
      - name: Deploy Prod
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ubuntu
          password: ${{ secrets.LIGHTSAIL_PASSWORD }}
          port : 22
          script: |
            docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
            docker pull sinkyoungdeok/fone-chatting
            docker-compose down 
            docker-compose up -d