name: SpotlessLint

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew
      - name: Spotless Apply
        run: ./gradlew spotlessApply
      - name: Spotless Check
        run: ./gradlew spotlessCheck