name: Test

on:
  pull_request:

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  DISCORD_QUESTION_URL: ${{ secrets.DISCORD_QUESTION_URL }}
  DISCORD_REPORT_URL: ${{ secrets.DISCORD_REPORT_URL }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew
      - name: Test With Gradle
        run: ./gradlew test koverXmlReport
      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 10
          min-coverage-changed-files: 10
          coverage-counter-type: LINE
